### ISSUE TITLE
Implement list of images and text block

### ISSUE THREAD

**Issue by jose-correia** [adobe-basel/summit-emea-team-2#43]
https://summit-emea.adobe.com/emea/

<img width="1125" alt="Screenshot 2023-05-09 at 11 05 27" src="https://user-images.githubusercontent.com/37300462/237048857-b6ed485c-1b64-4f77-9625-663adf4148fa.png">

**Comment by QuentinVecchio** [comment]
Should be fixed by #26 

<img width="988" alt="image" src="https://github.com/adobe-basel/summit-emea-team-2/assets/16210863/fcd090ef-3f9b-4d3b-939c-410a2bdd4b72">
