### ISSUE TITLE
Implement sponsors landing page block

### ISSUE THREAD

**Issue by jose-correia** [adobe-basel/summit-emea-team-2#48]
https://summit-emea.adobe.com/emea/

<img width="1102" alt="Screenshot 2023-05-09 at 15 08 32" src="https://github.com/adobe-basel/summit-emea-team-2/assets/37300462/7934e4d3-50a2-4726-b675-a09800b45608">

**Comment by nonanalou** [comment]
Notes:
- When i add a text with a link in the Word doc, it turns into a btn. [(Franklin doc)](https://www.hlx.live/developer/block-collection/links) So I guess I will have to remove the btn styling.
