### ISSUE TITLE
Featured speaker cards

### ISSUE THREAD

**Issue by alexcarol** [adobe-basel/summit-emea-team-2#7]
https://summit-emea.adobe.com/emea/

![image](https://user-images.githubusercontent.com/1713440/236760043-98da7974-7fa2-4579-b2d9-7217c0fa3be3.png)

**Comment by prangish** [comment]
Done, implemented in https://github.com/adobe-basel/summit-emea-team-2/pull/53
https://main--summit-emea-team-2--adobe-basel.hlx.page/
